on:
  push:
    branches:
      - develop

jobs:
  generate-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Swagger Codegen CLI
        run: |
          wget https://oss.sonatype.org/content/repositories/releases/io/swagger/codegen/v3/swagger-codegen-cli/3.0.29/swagger-codegen-cli-3.0.29.jar -O swagger-codegen-cli.jar

      - name: Create output directory
        run: mkdir -p typescript-client

      - name: Generate TypeScript client
        run: |
          java -jar swagger-codegen-cli.jar generate \
          -i openapi/apidoc.json \
          -l typescript-fetch \
          -o typescript-client

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Change to your desired Node.js version
          registry-url: 'https://maven.pkg.github.com/CarlosribesDev/booking-client'
      - name: Create package.json in typescript-client
        run: |
          echo '{' > typescript-client/package.json
          echo '  "name": "my-typescript-client",' >> typescript-client/package.json
          echo '  "version": "1.0.0",' >> typescript-client/package.json
          echo '  "description": "Client library for my API",' >> typescript-client/package.json
          echo '  "main": "index.js",' >> typescript-client/package.json
          echo '  "scripts": {' >> typescript-client/package.json
          echo '    "test": "echo \\"Error: no test specified\\" && exit 1"' >> typescript-client/package.json
          echo '  },' >> typescript-client/package.json
          echo '  "author": "ribi-code",' >> typescript-client/package.json
          echo '  "license": "MIT"' >> typescript-client/package.json
          echo '}' >> typescript-client/package.json

      - name: Publish TypeScript client to GitHub Packages
        run: |
          cd typescript-client
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_TOKEN }}