on:
  push:
    branches:
      - develop

jobs:
  generate-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Swagger Codegen CLI
        run: |
          wget https://oss.sonatype.org/content/repositories/releases/io/swagger/codegen/v3/swagger-codegen-cli/3.0.29/swagger-codegen-cli-3.0.29.jar -O swagger-codegen-cli.jar

      - name: Create output directory
        run: mkdir -p typescript-client

      - name: Generate TypeScript client
        run: |
          java -jar swagger-codegen-cli.jar generate \
          -i openapi/apidoc.json \
          -l typescript-fetch \
          -o typescript-client

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Change to your desired Node.js version
          registry-url: 'https://npm.pkg.github.com'
          scope: '@Bunker-Code'
      - name: Copy package.json to typescript-client
        run: cp package.json typescript-client/

      - name: Publish TypeScript client to GitHub Packages
        run: |
          cd typescript-client
          npm i
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_TOKEN }}