on:
  push:
    branches:
      - develop

jobs:
  generate-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Swagger Codegen CLI
        run: |
          wget https://oss.sonatype.org/content/repositories/releases/io/swagger/codegen/v3/swagger-codegen-cli/3.0.29/swagger-codegen-cli-3.0.29.jar -O swagger-codegen-cli.jar

      - name: Generate TypeScript client
        run: |
          java -jar swagger-codegen-cli.jar generate \
          -i openapi/apidoc.json \
          -l typescript-axios \
          -o typescript-client

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Change to your desired Node.js version
          registry-url: 'https://maven.pkg.github.com/CarlosribesDev/booking-client'
      - name: show files
        run: |
          ls -la

      - name: Publish TypeScript client to GitHub Packages
        run: |
          cd typescript-client
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_TOKEN }}